services:
  nats:
    image: nats:2
    command: ["-js"]
    ports: ["4222:4222", "8222:8222"]

  dash:
    build:
      context: .
      dockerfile: python/Dockerfile
    command: ["streamlit", "run", "python/dash/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    volumes:
      - ./:/app
    ports: ["8501:8501"]
    depends_on: [nats]
