# Virtual Lab Configuration
# This configuration defines the virtual lab environment for testing BGP anomaly detection

lab:
  name: "BGP Anomaly Detection Virtual Lab"
  version: "1.0.0"
  description: "Virtual lab environment for testing ML-based BGP anomaly detection with realistic data generation"

# Network Topology Configuration
topology:
  # Core network devices
  devices:
    spine_switches:
      count: 2
      model: "Cisco Nexus 9000"
      roles: ["spine"]
      interfaces: 48
      
    tor_switches:
      count: 4
      model: "Cisco Nexus 3000"
      roles: ["tor"]
      interfaces: 24
      
    leaf_switches:
      count: 8
      model: "Cisco Catalyst 9300"
      roles: ["leaf"]
      interfaces: 12

  # BGP Configuration
  bgp:
    as_numbers:
      spine_as: 65001
      tor_as: 65002
      leaf_as: 65003
    peer_relationships:
      - type: "spine-tor"
        count: 8
      - type: "tor-leaf"
        count: 16
    prefix_pools:
      - network: "10.0.0.0/8"
        count: 1000
      - network: "172.16.0.0/12"
        count: 500
      - network: "192.168.0.0/16"
        count: 200

# Data Generation Configuration
data_generation:
  # BGP Telemetry
  bgp_telemetry:
    enabled: true
    update_frequency: 1.0  # seconds
    base_announcements_per_second: 10
    base_withdrawals_per_second: 2
    anomaly_injection:
      enabled: true
      frequency: 0.1  # 10% chance per update
      types: ["link_failure", "bgp_reset", "prefix_hijack", "route_flap"]
      
  # Syslog Data
  syslog:
    enabled: true
    base_messages_per_second: 5
    severity_distribution:
      info: 0.6
      warning: 0.25
      error: 0.1
      critical: 0.05
    message_types:
      - "interface_up_down"
      - "bgp_neighbor_changes"
      - "ospf_events"
      - "system_events"
      - "security_events"

# Scaling Configuration
scaling:
  # Progressive scaling phases
  phases:
    - name: "baseline"
      duration_minutes: 5
      bgp_multiplier: 1.0
      syslog_multiplier: 1.0
      
    - name: "light_load"
      duration_minutes: 10
      bgp_multiplier: 2.0
      syslog_multiplier: 1.5
      
    - name: "medium_load"
      duration_minutes: 15
      bgp_multiplier: 5.0
      syslog_multiplier: 3.0
      
    - name: "heavy_load"
      duration_minutes: 20
      bgp_multiplier: 10.0
      syslog_multiplier: 5.0
      
    - name: "stress_test"
      duration_minutes: 10
      bgp_multiplier: 20.0
      syslog_multiplier: 10.0

# Message Bus Configuration
message_bus:
  type: "nats"
  servers: ["nats://localhost:4222"]
  subjects:
    bgp_updates: "bgp.updates"
    syslog_messages: "syslog.messages"
    telemetry_data: "telemetry.data"
    processed_features: "features.processed"
    anomaly_alerts: "anomaly.alerts"

# Preprocessing Pipeline Configuration
preprocessing:
  # Feature extraction based on Feltin 2023 paper
  feature_extraction:
    time_windows:
      - 30  # seconds
      - 60  # seconds
      - 300 # seconds
    features:
      bgp:
        - "announcement_rate"
        - "withdrawal_rate"
        - "as_path_churn"
        - "prefix_churn"
        - "peer_availability"
      syslog:
        - "error_rate"
        - "warning_rate"
        - "message_frequency"
        - "device_health_score"
        - "event_correlation"
    
  # Data transformation
  transformation:
    normalization: "z_score"
    aggregation_method: "sliding_window"
    correlation_window: 60  # seconds

# ML Pipeline Configuration
ml_pipeline:
  # Matrix Profile Configuration
  matrix_profile:
    window_bins: 64
    discord_threshold: 2.5
    gpu_acceleration: true
    
  # Feature Selection (Feltin 2023 approach)
  feature_selection:
    method: "mutual_information"
    max_features: 20
    correlation_threshold: 0.8
    
  # Anomaly Detection
  anomaly_detection:
    algorithms:
      - "matrix_profile"
      - "isolation_forest"
      - "one_class_svm"
    ensemble_voting: true
    confidence_threshold: 0.7

# Monitoring and Alerting
monitoring:
  metrics_collection: true
  dashboard_enabled: true
  alerting:
    email: false
    slack: false
    webhook: true
    webhook_url: "http://localhost:8080/alerts"
    
# Logging Configuration
logging:
  level: "INFO"
  file: "virtual_lab/logs/lab.log"
  max_size: "100MB"
  backup_count: 5
