# Map device identifiers (router-id or hostname) to roles
roles:
  10.0.0.1: rr
  10.0.0.2: rr
  10.0.1.1: spine
  10.0.1.2: spine
  10.0.2.1: tor
  10.0.2.2: tor
  10.0.3.1: edge
  10.0.3.2: edge
  10.0.10.11: server
  10.0.10.12: server
  # ... add remaining hosts
thresholds:
  edge_local_prefix_max: 100        # classify as edge-local if fewer than this
  edge_local_pct_table_max: 0.01    # or <1% of total table
  correlation_window_secs: 60
binning:
  bin_seconds: 30
  window_bins: 64                   # MP subsequence length in bins
