asn: 65000
router_id: 10.255.255.1
bind_addr: 0.0.0.0
peers:
  - address: 10.0.1.1
    remote_as: 65011
    passive: true
  - address: 10.0.1.2
    remote_as: 65011
    passive: true
  - address: 10.0.2.1
    remote_as: 65021
    passive: true
  - address: 10.0.2.2
    remote_as: 65022
    passive: true
  - address: 10.0.3.1
    remote_as: 65031
    passive: true
  - address: 10.0.3.2
    remote_as: 65032
    passive: true
# add servers if they peer directly to collector; otherwise ToRs cover them
nats:
  url: nats://localhost:4222
  subject: bgp.updates
