name: BGP Failure Detection CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-go:
    name: Test Go BGP Collector
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
    
    - name: Build Go collector
      run: go build -v ./cmd/collector
    
    - name: Run Go tests
      run: go test -v ./...

  test-python:
    name: Test Python Pipeline
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest black ruff
    
    - name: Lint with ruff
      run: ruff check python
    
    - name: Format check with black
      run: black --check python
    
    - name: Test Python imports
      run: python -c "from python.utils.schema import BGPUpdate, FeatureBin; print('✅ Python imports successful')"

  docker-build:
    name: Test Docker Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker images
      run: |
        docker build -f python/Dockerfile -t bgp-dashboard .
        docker images bgp-dashboard
