name: BGP Failure Detection CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:

  test-python:
    name: Test Python Pipeline
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest black ruff
    
    - name: Lint with ruff
      run: ruff check src
    
    - name: Format check with black
      run: black --check src
    
    - name: Test Python imports
      run: python -c "from src.utils.schema import BGPUpdate, FeatureBin; print('✅ Python imports successful')"

  docker-build:
    name: Test Docker Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker images
      run: |
        docker build -f src/Dockerfile -t bgp-dashboard .
        docker images bgp-dashboard
